apiVersion: v1
kind: Service
metadata:
  name: knote
  namespace: backend
spec:
  selector:
    app: knote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort