apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-of-apps
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-apps
    repoURL: 'https://github.com/dinushchathurya/argocd-app-of-apps.git'
    targetRevision: develop
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true