apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-backend
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev-backend
    server: https://kubernetes.default.svc
  project: app-of-apps
  source:
    path: my-apps/frontend
    repoURL: https://github.com/dinushchathurya/argocd-app-of-apps.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true