apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: frontend
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: frontend
    server: https://kubernetes.default.svc
  project: app-of-apps
  source:
    path: my-apps/frontend/overlays/dev
    repoURL: https://github.com/dinushchathurya/argocd-app-of-apps.git
    targetRevision: develop