apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: backend
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: backend
    server: https://kubernetes.default.svc
  project: app-of-apps
  source:
    path: my-apps/backend/overlays/prod
    repoURL: https://github.com/dinushchathurya/argocd-app-of-apps.git
    targetRevision: develop